### ISSUE TITLE
Instead of renderBefore, use contextualizeBefore

### ISSUE THREAD

**Issue by julrichkieffer** [grassator/docpad-plugin-datefromfilename#6]
Could you use an earlier Docpad event so that other plugins that rely on the document date can process correctly. I suggest `contextualizeBefore`.

For example, the [Scheduling Plugin](https://github.com/miletbaker/docpad-plugin-scheduling) is currently using the file system date as your plugin is executed *after*. Note: [Issue](https://github.com/miletbaker/docpad-plugin-scheduling/issues/2)

**Comment by grassator** [comment]
@julrichkieffer I would be happy to accept a PR that fixes that
